In [1]:
# Create matrix A
A <- matrix(c(1, 2, 3, 4, 5, 6, 7, 8, 9), nrow = 3, ncol = 3)

# Create matrix B
B <- matrix(c(9, 8, 7, 6, 5, 4, 3, 2, 1), nrow = 3, ncol = 3)

# Transpose of matrix A
A_transpose <- t(A)

# Transpose of matrix B
B_transpose <- t(B)

# Addition of matrices A and B
sum_AB <- A + B

# Subtraction of matrices A and B
diff_AB <- A - B

# Output the results
cat("Matrix A:\n")
print(A)
cat("\n")

cat("Matrix B:\n")
print(B)
cat("\n")

cat("Transpose of matrix A:\n")
print(A_transpose)
cat("\n")

cat("Transpose of matrix B:\n")
print(B_transpose)
cat("\n")

cat("Addition of matrices A and B:\n")
print(sum_AB)
cat("\n")

cat("Subtraction of matrices A and B:\n")
print(diff_AB)
cat("\n")


Matrix A:
     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9

Matrix B:
     [,1] [,2] [,3]
[1,]    9    6    3
[2,]    8    5    2
[3,]    7    4    1

Transpose of matrix A:
     [,1] [,2] [,3]
[1,]    1    2    3
[2,]    4    5    6
[3,]    7    8    9

Transpose of matrix B:
     [,1] [,2] [,3]
[1,]    9    8    7
[2,]    6    5    4
[3,]    3    2    1

Addition of matrices A and B:
     [,1] [,2] [,3]
[1,]   10   10   10
[2,]   10   10   10
[3,]   10   10   10

Subtraction of matrices A and B:
     [,1] [,2] [,3]
[1,]   -8   -2    4
[2,]   -6    0    6
[3,]   -4    2    8

